### ISSUE TITLE
Cancan nested hash condition produces invalid SQL

### ISSUE THREAD

**Issue by mcm-ham** [DockYard/postgres_ext-serializers#21]
If I serialize this:
```ruby
Tag.where(note: {name: 'title'})
```
It produces SQL like this:
```sql
SELECT "tags"."id", 
       "tags"."name", 
       "tags"."note_id" 
FROM   "tags" 
WHERE  "note"."name" = 'Title'
```
Instead of doing a table join on offers.

**Comment by danmcclain** [comment]
Was this possible without explicitly joining?

**Comment by mcm-ham** [comment]
Sorry no it's not. I just got confused with [cancancan](https://github.com/CanCanCommunity/cancancan) syntax which allows:
```rb
can :index, Tag, note: {name: 'title'}
```
But after adding postgres_ext-serializers it then generates invalid sql like above.

A workaround people can use is:
```rb
class Tag < ActiveRecord::Base
  scope :name_is_title, -> { joins(:note).where(notes: {name:'title'}) }
end

can :index, Tag, Tag.name_is_title do |tag|
  tag.note.title == 'title'
end
```

**Comment by felixbuenemann** [comment]
Need to check if this is still an issue.

**Comment by felixbuenemann** [comment]
As far as I can seem this works fine on master, but you have to use `where(notes: { name: 'Title' })` (not `:note`) or it won't work. That's because activerecord does not expand symbols in the were to the table name of the joined relation. It has nothing to do with postgres_ext-serializers.

If this was previously broken, then either #44 or #45 has fixed it.

**Comment by felixbuenemann** [comment]
Btw. if you don't want to manually specify the correct table name in the `where`, you can use `merge`:

```ruby
Tag.joins(:note).merge(Note.where(name: 'Title'))
```
